import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * rows: array of items like
  * {
   *   id, name, designation, rating (number or string), notes, photo(dataURL optional)
    *   // tolerant aliases also supported: employeeId, empId, fullName, role, position, ratingPercent, performance, score, comment(s), remark
     * }
      */
      export async function downloadTeamReportPDF(
        rows: any[],
          opts?: { title?: string; departmentId?: string; dateFrom?: string; dateTo?: string }
          ) {
            const { title, departmentId, dateFrom, dateTo } = opts || {};
              const doc = new jsPDF({ orientation: "p", unit: "pt", format: "a4" });

                const now = new Date().toLocaleString();
                  const reportTitle = title || "Team Performance Report";

                    // ---- unified page geometry ----
                      const pageWidth = doc.internal.pageSize.getWidth();
                        const sideMargin = 20; // tiny, even margins
                          const contentX = sideMargin;

                            // ---- Header (centered title, metadata aligned with table edges) ----
                              doc.setFontSize(14);
                                doc.text(reportTitle, pageWidth / 2, 40, { align: "center" });
                                  doc.setFontSize(10);
                                    doc.text(`Department: ${departmentId || "all"}`, contentX, 60);
                                      doc.text(`Range: ${dateFrom || "—"} — ${dateTo || "—"}`, contentX, 75);
                                        doc.text(`Generated: ${now}`, contentX, 90);

                                          // Build table data
                                            const headers = ["Photo", "Id", "Name", "Designation", "Rating", "Notes"];
                                              const body = (rows || []).map((r: any) => {
                                                  const id =
                                                        r.id ?? r.employeeId ?? r.empId ?? r.code ?? "—";
                                                            const name =
                                                                  r.name ?? r.fullName ?? r.employeeName ?? "—";
                                                                      const designation =
                                                                            r.designation ?? r.role ?? r.position ?? "—";
                                                                                const ratingRaw =
                                                                                      r.rating ?? r.ratingPercent ?? r.performanceRating ?? r.performance ?? r.score ?? null;
                                                                                          const rating =
                                                                                                typeof ratingRaw === "number" ? `${ratingRaw}%` : (ratingRaw ?? "—");
                                                                                                    const notes =
                                                                                                          r.notes ?? r.comment ?? r.comments ?? r.remark ?? "—";
                                                                                                              const photo =
                                                                                                                    r.photo ?? r.avatar ?? r.image ?? ""; // dataURL shows; external URLs are ignored
                                                                                                                        return [photo, id, name, designation, rating, notes];
                                                                                                                          });

                                                                                                                            // ---- Centered table layout ----
                                                                                                                              // Base widths for fixed columns
                                                                                                                                const wPhoto = 56;  // enough so header doesn't wrap
                                                                                                                                  const wId    = 70;
                                                                                                                                    const wName  = 150;
                                                                                                                                      const wRole  = 120;
                                                                                                                                        const wRate  = 60;

                                                                                                                                          // Compute the maximum table width allowed (respect tiny page margins)
                                                                                                                                            const maxTableWidth = pageWidth - sideMargin * 2;

                                                                                                                                              // Notes gets the rest of the width, but never less than this:
                                                                                                                                                const minNotes = 180;

                                                                                                                                                  // First, compute tentative notes width to fill the line:
                                                                                                                                                    let wNotes = maxTableWidth - (wPhoto + wId + wName + wRole + wRate);

                                                                                                                                                      // If notes would be too small, clamp it and (optionally) steal a bit from Name/Role to keep balance
                                                                                                                                                        if (wNotes < minNotes) {
                                                                                                                                                            const deficit = minNotes - wNotes;
                                                                                                                                                                // try to shave 2/3 from Name and 1/3 from Role, but don't go below sensible floors
                                                                                                                                                                    let shaveName = Math.min(deficit * 0.66, Math.max(0, wName - 120));
                                                                                                                                                                        let shaveRole = Math.min(deficit * 0.34, Math.max(0, wRole - 100));
                                                                                                                                                                            const shaved = shaveName + shaveRole;

                                                                                                                                                                                // apply shaving
                                                                                                                                                                                    const finalWName = wName - shaveName;
                                                                                                                                                                                        const finalWRole = wRole - shaveRole;

                                                                                                                                                                                            // recompute notes width (if we couldn't shave enough, notes gets min and total shrinks a bit)
                                                                                                                                                                                                wNotes = Math.max(minNotes, maxTableWidth - (wPhoto + wId + finalWName + finalWRole + wRate));

                                                                                                                                                                                                    // finalize widths
                                                                                                                                                                                                        drawTable({
                                                                                                                                                                                                              photo: wPhoto,
                                                                                                                                                                                                                    id: wId,
                                                                                                                                                                                                                          name: finalWName,
                                                                                                                                                                                                                                role: finalWRole,
                                                                                                                                                                                                                                      rate: wRate,
                                                                                                                                                                                                                                            notes: wNotes,
                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                      // plenty of space: use the full width
                                                                                                                                                                                                                                                          drawTable({
                                                                                                                                                                                                                                                                photo: wPhoto,
                                                                                                                                                                                                                                                                      id: wId,
                                                                                                                                                                                                                                                                            name: wName,
                                                                                                                                                                                                                                                                                  role: wRole,
                                                                                                                                                                                                                                                                                        rate: wRate,
                                                                                                                                                                                                                                                                                              notes: wNotes,
                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                      function drawTable(widths: {
                                                                                                                                                                                                                                                                                                          photo: number; id: number; name: number; role: number; rate: number; notes: number;
                                                                                                                                                                                                                                                                                                            }) {
                                                                                                                                                                                                                                                                                                                // Total width with these column sizes
                                                                                                                                                                                                                                                                                                                    const totalTableWidth =
                                                                                                                                                                                                                                                                                                                          widths.photo + widths.id + widths.name + widths.role + widths.rate + widths.notes;

                                                                                                                                                                                                                                                                                                                              // Center the table by setting equal left/right margins around the exact width
                                                                                                                                                                                                                                                                                                                                  const centerMargin = Math.max(0, (pageWidth - totalTableWidth) / 2);

                                                                                                                                                                                                                                                                                                                                      autoTable(doc, {
                                                                                                                                                                                                                                                                                                                                            head: [headers],
                                                                                                                                                                                                                                                                                                                                                  body,
                                                                                                                                                                                                                                                                                                                                                        startY: 110,
                                                                                                                                                                                                                                                                                                                                                              margin: { left: centerMargin, right: centerMargin },
                                                                                                                                                                                                                                                                                                                                                                    tableWidth: totalTableWidth,

                                                                                                                                                                                                                                                                                                                                                                          styles: {
                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 9,
                                                                                                                                                                                                                                                                                                                                                                                          cellPadding: 8,
                                                                                                                                                                                                                                                                                                                                                                                                  overflow: "linebreak",  // wrap long notes
                                                                                                                                                                                                                                                                                                                                                                                                          lineWidth: 0.2,
                                                                                                                                                                                                                                                                                                                                                                                                                  valign: "top",
                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                              headStyles: {
                                                                                                                                                                                                                                                                                                                                                                                                                                      fillColor: [30, 41, 59],
                                                                                                                                                                                                                                                                                                                                                                                                                                              textColor: 255,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              cellPadding: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      overflow: "hidden",     // don't wrap headers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alternateRowStyles: { fillColor: [246, 248, 252] },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        columnStyles: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0: { cellWidth: widths.photo },                // Photo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1: { cellWidth: widths.id },                   // Id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2: { cellWidth: widths.name },                 // Name
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        3: { cellWidth: widths.role },                 // Designation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                4: { cellWidth: widths.rate, halign: "right" },// Rating
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        5: { cellWidth: widths.notes },                // Notes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // draw thumbnail if we get a data URL in Photo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          didDrawCell: (data) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (data.section === "body" && data.column.index === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const val = data.cell.raw as string | undefined;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (val && typeof val === "string" && val.startsWith("data:image")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const { x, y, height } = data.cell as any;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const size = Math.min(height - 6, 22);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          doc.addImage(val, "PNG", x + 5, y + 3, size, size, undefined, "FAST");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (data.cell as any).text = [""];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    didDrawPage: (data) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            doc.setFontSize(9);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    doc.text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              `Page ${doc.getNumberOfPages()}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        data.settings.margin.left,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  doc.internal.pageSize.height - 20
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const fname =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            (reportTitle.toLowerCase().replace(/\s+/g, "_") || "performance_report") + ".pdf";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              doc.save(fname);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              