// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gikbgkqctnytvhoqlnbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdpa2Jna3FjdG55dHZob3FsbmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjUyMTksImV4cCI6MjA2NDUwMTIxOX0.xS-NTcU9hxlMoXNoZjIjnrabN4jZID3DWyneyElePVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);